version: '2'

# This compose file is just an example. Create your own to launch your own Aegir cluster

services:

  devshop:
    image: devshop/server:local
    ports:
      - "80:80"
      - "2222:22"
    hostname: devshop.local.computer
    extra_hosts:
      - "drpl8.testenv.devshop.local.computer:127.0.0.1"
    environment:
      # Change to use a different database host.
      DATABASE_HOST: localhost
      MYSQL_ROOT_PASSWORD: strongpassword
      AEGIR_MAKEFILE: /usr/share/devshop/build-devmaster-dev.make.yml
      AEGIR_PROFILE: devmaster
      AEGIR_VERSION: 1.x
      PROVISION_VERSION: 7.x-3.x
      AEGIR_HOSTMASTER_ROOT: /var/aegir/devmaster-1.x
      XDEBUG_CONFIG: "remote_host=172.17.0.1 idekey=PHPSTORM"
      PHP_IDE_CONFIG: "serverName=devshop.local.computer"

      # To allow the devmaster container to launch other docker containers, we need the host's path to aegir home directory.
      HOST_AEGIR_HOME: /home/jon/Projects/devshop/aegir-home
      PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/share/devshop/bin"
      # @TODO: We can't define the service type here.
      # The Provision classes for this service type MUST be available in
      # provision project, because at this point, the devmaster site might not
      # be there, and the .drushrc.php used to include Provision classes in
      # Hosting modules doesn't exist. Until we add more services to provision
      # itself, or include additional libraries, we can't use this.
      # This would work for changing to nginx, once the container supports that.
      # AEGIR_HTTP_SERVICE_TYPE: https_apache

      # Set any desired ansible configuration items here. (Only affects containers at run time, not build time.)
      ANSIBLE_VERBOSITY: 0

      # Add additional files you would like to output in the container logs here, separated by a space.
      DEVSHOP_ENTRYPOINT_LOG_FILES: "/var/log/aegir/*"
      DEVSHOP_TESTS_ASSETS_PATH: "/usr/share/devshop/.github/test-assets"

    privileged: true
    volumes:
      - ./aegir-home:/var/aegir:delegated
      - ./devmaster:/var/aegir/devmaster  #-1.x/profiles/devmaster:delegated
      - ./:/usr/share/devshop:delegated
      - ./provision:/usr/share/drush/commands/provision:delegated
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/lib/mysql
      - /var/logs/aegir
      - $HOME/.ssh:/var/aegir/.ssh
      # Uncomment when developing the the entrypoint script for rapid docker-compose up runs.
      # - ./docker/bin/entrypoint:/usr/local/bin/entrypoint:delegated

# Database container is now optional: for local development just use the devshop/server container.
#  database:
#    image: mariadb
#    logging:
#      driver: none
#    environment:
#      MYSQL_ROOT_PASSWORD: strongpassword

  admin:
    image: phpmyadmin/phpmyadmin
    links:
      - devshop:db
    ports:
      - 8080:80

#  selenium:
#    image: selenium/standalone-chrome-debug:3.4.0-dysprosium
#    ports:
#      - 4444:4444
#      - 5900:5900
