# Aegir Roles


- name: geerlingguy.php-mysql
  version: 2.0.2

- name: geerlingguy.php
  version: 3.7.0

- name: geerlingguy.php-versions
  version: 3.1.3

- name: geerlingguy.repo-remi
  version: 1.2.0

- name: geerlingguy.git
  version: 2.0.4

- name: geerlingguy.composer
  version: 1.7.3

- name: geerlingguy.mysql
  version: 2.9.5

- name: geerlingguy.apache
  version: 3.0.3

- name: geerlingguy.supervisor
  version: 2.0.2

- name: geerlingguy.php-versions
  version: 4.0.2
