##
# DevShop: DevMaster Server with Apache
#

---
- hosts: all
  user: root
  vars_files:
    - vars.vagrant.yml
  roles:
    - opendevshop.users
    - opendevshop.apache
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.composer
    - opendevshop.devmaster
