name: Install
on: [push]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  install:
    # @TODO: Reconfigure the install script test to use a bare container. The GitHub Workflow images have many things pre-installed:
    #  https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners#ubuntu-1604-lts
    if: false
    name: Shell Script
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1

    - name: Move code to /usr/share/devshop
      run: cp -rf $PWD /usr/share/devshop

    - name: Run install.sh Script
      run: sudo -H bash /usr/share/devshop/install.sh --playbook=playbook.testing.yml --hostname=devshop.local.computer

    - name: Run tests/devshop-tests.sh Script
      run:  sudo su aegir -c "bash  /usr/share/devshop/tests/devshop-tests.sh"
