name: Tests

on: [push]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  lint:
    name: Ansible Lint
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1

    # @TODO: Attempted to cache the pip packages, doesn't seem to work in subfolders.
    #      - uses: actions/cache@v1
    #        id: cache
    #        with:
    #          path: .cache/pip
    #          key: ${{ runner.os }}-pip-${{ hashFiles('**/roles/opendevshop.devmaster/molecule/requirements.txt') }}
    #          restore-keys: |
    #                ${{ runner.os }}-test

    - name: Install Ansible Molecule
      if: steps.cache.outputs.cache-hit != 'true'
      working-directory: ./roles/opendevshop.devmaster/molecule
      run: |
        pwd
        ls -la
        python -m pip install --upgrade pip
        pip install -r molecule-requirements.txt

    - name: Run `molecule lint`
      working-directory: ./roles/opendevshop.devmaster
      run: molecule lint

  build:
    name: Build DevShop
    runs-on: ubuntu-18.04
    steps:

    - uses: actions/checkout@v1
    - name: Get Composer Cache Directory
      id: composer-cache
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"

    - uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Create DevShop Server Image
      run: bin/robo prepare:containers -v

    - name: Write GITHUB environment variables  to a file so the container inherits the GITHUB_ variables.
      run: env | grep GITHUB_ > .ci.env

    - name: Run DevShop Server and tests
      run: bin/robo up --test --skip-source-prep -v

    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: test-assets
        path: ./.github/test-assets
